//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackingCygest.Resource {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PackingCygest.Resource.AppResource", typeof(AppResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD.
        /// </summary>
        internal static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string BtnClear {
            get {
                return ResourceManager.GetString("BtnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well done,you have.
        /// </summary>
        internal static string CompleteMsg1 {
            get {
                return ResourceManager.GetString("CompleteMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to completed your PackingCygest.
        /// </summary>
        internal static string CompleteMsg2 {
            get {
                return ResourceManager.GetString("CompleteMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Delivery.
        /// </summary>
        internal static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High_Button.png.
        /// </summary>
        internal static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High_Button_Red.png.
        /// </summary>
        internal static string HighRed {
            get {
                return ResourceManager.GetString("HighRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click_to_take_pic.png.
        /// </summary>
        internal static string ImageClickToTakePic {
            get {
                return ResourceManager.GetString("ImageClickToTakePic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR SCAN BARCODE.
        /// </summary>
        internal static string LblAssignAnother {
            get {
                return ResourceManager.GetString("LblAssignAnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign barcode.
        /// </summary>
        internal static string LblAssignBarcode {
            get {
                return ResourceManager.GetString("LblAssignBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode missing.
        /// </summary>
        internal static string LblBarcodeMissing {
            get {
                return ResourceManager.GetString("LblBarcodeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel .
        /// </summary>
        internal static string lblCancel {
            get {
                return ResourceManager.GetString("lblCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATEGORY.
        /// </summary>
        internal static string LblCategory {
            get {
                return ResourceManager.GetString("LblCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        internal static string LblClient {
            get {
                return ResourceManager.GetString("LblClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPLETED.
        /// </summary>
        internal static string LblCompletedTile {
            get {
                return ResourceManager.GetString("LblCompletedTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIGURATION.
        /// </summary>
        internal static string LblConfig {
            get {
                return ResourceManager.GetString("LblConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTROLS.
        /// </summary>
        internal static string LblControl {
            get {
                return ResourceManager.GetString("LblControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELIVERY.
        /// </summary>
        internal static string LblDelivery {
            get {
                return ResourceManager.GetString("LblDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELIVERY.
        /// </summary>
        internal static string LblDelivery1 {
            get {
                return ResourceManager.GetString("LblDelivery1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISMOUNTING.
        /// </summary>
        internal static string LblDismounting {
            get {
                return ResourceManager.GetString("LblDismounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double barcodes.
        /// </summary>
        internal static string LblDoubleBarcodes {
            get {
                return ResourceManager.GetString("LblDoubleBarcodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump Not sent.
        /// </summary>
        internal static string lblDumpNotSent {
            get {
                return ResourceManager.GetString("lblDumpNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump was  sent.
        /// </summary>
        internal static string lblDumpSent {
            get {
                return ResourceManager.GetString("lblDumpSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump.
        /// </summary>
        internal static string lblDumpTitle {
            get {
                return ResourceManager.GetString("lblDumpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string LblEnd {
            get {
                return ResourceManager.GetString("LblEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string LblEndControlNext {
            get {
                return ResourceManager.GetString("LblEndControlNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End PackingCygest.
        /// </summary>
        internal static string LblEndPackingCygest {
            get {
                return ResourceManager.GetString("LblEndPackingCygest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string lblError {
            get {
                return ResourceManager.GetString("lblError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File:.
        /// </summary>
        internal static string LblFile {
            get {
                return ResourceManager.GetString("LblFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Furniture.
        /// </summary>
        internal static string LblFurniture {
            get {
                return ResourceManager.GetString("LblFurniture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELIVERY.
        /// </summary>
        internal static string LblHeading {
            get {
                return ResourceManager.GetString("LblHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string LblHomeAppliance {
            get {
                return ResourceManager.GetString("LblHomeAppliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid barcode.
        /// </summary>
        internal static string LblInvalidBarcode {
            get {
                return ResourceManager.GetString("LblInvalidBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign on the signature pad.
        /// </summary>
        internal static string LblInvalidSignature {
            get {
                return ResourceManager.GetString("LblInvalidSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ITEM.
        /// </summary>
        internal static string LblItem {
            get {
                return ResourceManager.GetString("LblItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known.
        /// </summary>
        internal static string LblKnown {
            get {
                return ResourceManager.GetString("LblKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTROL.
        /// </summary>
        internal static string LblLoadEndControlTitle {
            get {
                return ResourceManager.GetString("LblLoadEndControlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MECHANICAL STATE.
        /// </summary>
        internal static string LblMechanicalState {
            get {
                return ResourceManager.GetString("LblMechanicalState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mover.
        /// </summary>
        internal static string LblMover {
            get {
                return ResourceManager.GetString("LblMover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Item.
        /// </summary>
        internal static string LblNewItem {
            get {
                return ResourceManager.GetString("LblNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Connection.
        /// </summary>
        internal static string lblNoConnection {
            get {
                return ResourceManager.GetString("lblNoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No network.
        /// </summary>
        internal static string LblNoNetwork {
            get {
                return ResourceManager.GetString("LblNoNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of items.
        /// </summary>
        internal static string LblNumberOfItems {
            get {
                return ResourceManager.GetString("LblNumberOfItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUMBER OF ITEMS :.
        /// </summary>
        internal static string LblNumItem {
            get {
                return ResourceManager.GetString("LblNumItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUMBER OF ITEMS EXPECTED :.
        /// </summary>
        internal static string LblNumItemExpct {
            get {
                return ResourceManager.GetString("LblNumItemExpct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUMBER OF ITEMS RECEIVED :.
        /// </summary>
        internal static string LblNumItemReceived {
            get {
                return ResourceManager.GetString("LblNumItemReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string lblOK {
            get {
                return ResourceManager.GetString("lblOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PACKED BY.
        /// </summary>
        internal static string LblPackingCygest {
            get {
                return ResourceManager.GetString("LblPackingCygest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHOTO AND COMMENT.
        /// </summary>
        internal static string LblPhotoAndComment {
            get {
                return ResourceManager.GetString("LblPhotoAndComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enable your network.
        /// </summary>
        internal static string LblPleaseEnableYourNetwork {
            get {
                return ResourceManager.GetString("LblPleaseEnableYourNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PackingCygest PROGRESS.
        /// </summary>
        internal static string LblProgress {
            get {
                return ResourceManager.GetString("LblProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reassemble.
        /// </summary>
        internal static string LblReassemble {
            get {
                return ResourceManager.GetString("LblReassemble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reassembled.
        /// </summary>
        internal static string LblReassembled {
            get {
                return ResourceManager.GetString("LblReassembled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REASSEMBLING.
        /// </summary>
        internal static string LblReassembling {
            get {
                return ResourceManager.GetString("LblReassembling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT A ROOM.
        /// </summary>
        internal static string LblRoom {
            get {
                return ResourceManager.GetString("LblRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Configuration.
        /// </summary>
        internal static string lblSave {
            get {
                return ResourceManager.GetString("lblSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred, cannot save. Please fill in all fields  .
        /// </summary>
        internal static string lblSaveError {
            get {
                return ResourceManager.GetString("lblSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save .
        /// </summary>
        internal static string lblSaveSuccessfully {
            get {
                return ResourceManager.GetString("lblSaveSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Barcode.
        /// </summary>
        internal static string LblScanBarcode {
            get {
                return ResourceManager.GetString("LblScanBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please scan an item first.
        /// </summary>
        internal static string LblScanItemError {
            get {
                return ResourceManager.GetString("LblScanItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature has been saved.
        /// </summary>
        internal static string LblSignatureSaveSuccessful {
            get {
                return ResourceManager.GetString("LblSignatureSaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        internal static string LblSize {
            get {
                return ResourceManager.GetString("LblSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string LblSuccess {
            get {
                return ResourceManager.GetString("LblSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYNCHRONISING.
        /// </summary>
        internal static string LblSynchro {
            get {
                return ResourceManager.GetString("LblSynchro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string LblUnknown {
            get {
                return ResourceManager.GetString("LblUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Loading.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading data...
        /// </summary>
        internal static string LoadingData {
            get {
                return ResourceManager.GetString("LoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string LoadingTextDone {
            get {
                return ResourceManager.GetString("LoadingTextDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait...
        /// </summary>
        internal static string LoadingTextWait {
            get {
                return ResourceManager.GetString("LoadingTextWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low_Button.png.
        /// </summary>
        internal static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low_Button_Red.png.
        /// </summary>
        internal static string LowRed {
            get {
                return ResourceManager.GetString("LowRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium_Button.png.
        /// </summary>
        internal static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium_Button_Red.png.
        /// </summary>
        internal static string MediumRed {
            get {
                return ResourceManager.GetString("MediumRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Scan Valid Barcode.
        /// </summary>
        internal static string MessageScanValidBarcode {
            get {
                return ResourceManager.GetString("MessageScanValidBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        internal static string MobileNumberPlaceholder {
            get {
                return ResourceManager.GetString("MobileNumberPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        internal static string MobileNumberplaceholderDisplay {
            get {
                return ResourceManager.GetString("MobileNumberplaceholderDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid barcode.
        /// </summary>
        internal static string MsgInvalidBarcode {
            get {
                return ResourceManager.GetString("MsgInvalidBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please scan a barcode..
        /// </summary>
        internal static string MsgScanBarcode {
            get {
                return ResourceManager.GetString("MsgScanBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature was clear..
        /// </summary>
        internal static string MsgSignatureClear {
            get {
                return ResourceManager.GetString("MsgSignatureClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NextButton {
            get {
                return ResourceManager.GetString("NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need Assistance?.
        /// </summary>
        internal static string PckAssistance {
            get {
                return ResourceManager.GetString("PckAssistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string PckBranch {
            get {
                return ResourceManager.GetString("PckBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string PckBranchDisplay {
            get {
                return ResourceManager.GetString("PckBranchDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        internal static string PckCountry {
            get {
                return ResourceManager.GetString("PckCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        internal static string PckCountryDisplay {
            get {
                return ResourceManager.GetString("PckCountryDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string PckLanguage {
            get {
                return ResourceManager.GetString("PckLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string PckLanguageDisplay {
            get {
                return ResourceManager.GetString("PckLanguageDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Quality.
        /// </summary>
        internal static string PckPhotoQuality {
            get {
                return ResourceManager.GetString("PckPhotoQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving all data..
        /// </summary>
        internal static string PhotoCommentTitle {
            get {
                return ResourceManager.GetString("PhotoCommentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Barcode.
        /// </summary>
        internal static string TitleWrongBarcode {
            get {
                return ResourceManager.GetString("TitleWrongBarcode", resourceCulture);
            }
        }
    }
}
